### ISSUE TITLE
FreeRTOS submodule doesn't have Linux port

### ISSUE THREAD

**Issue by johnathancn** [lobaro/FreeRTOS-rust#34]
thread 'main' panicked at 'Directory freertos_port_dir does not exist: FreeRTOS-Kernel/portable/GCC/Linux', freertos-rust-examples/build.rs:61:38

Looks like this is recent regression following change from in-tree copy of Kernel to submodule. 
I checked upstream and can't find trace of that Linux folder ever being there, maybe it was added to the local copy in this repo

**Comment by schteve** [comment]
Thanks for catching this - the example builds don't work for me even before the submodule change so I didn't get to see this break myself. Agree the original source of the Linux port should be included.

Out of curiosity, since I see you have a proposed fix, does the Linux port build and run for you now with a simple build invocation something like this?
`cargo +nightly build --example linux --target x86_64-unknown-linux-gnu`

**Comment by johnathancn** [comment]
Yes, with my proposed fixes, that simple build command now works. Keep in mind, the PR also includes a hack fix for the other "cpu_hz" issue I raised.

Also note, when I first raised the issue I didn't know the origin of the Linux port code, but I later found it originated from [freertos-addons](https://github.com/michaelbecker/freertos-addons) 
so my fix involves adding that as an additional submodule.

**Comment by schteve** [comment]
Yeah it must be something on my side then, I applied your proposed fixes but still get other errors (apparently unrelated to these issues or your fixes). I will try to sort it out, since I know the build should work I'd like to see it working on my end before merging your new PR.
