### ISSUE TITLE
linux port: configCPU_CLOCK_HZ not defined

### ISSUE THREAD

**Issue by johnathancn** [lobaro/FreeRTOS-rust#35]
cargo:warning=/home/void/FreeRTOS-rust/freertos-rust/src/freertos/shim.c: In function 'freertos_rs_get_configCPU_CLOCK_HZ':
  cargo:warning=/home/void/FreeRTOS-rust/freertos-rust/src/freertos/shim.c:117:10: error: 'configCPU_CLOCK_HZ' undeclared (first use in this function)
  cargo:warning=  117 |   return configCPU_CLOCK_HZ;
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~

I realize this probably needs be defined in the examples / FreeRTOSConfig.h . Not sure what value to put there though...

**Comment by schteve** [comment]
Looks like this isn't defined on the win port either, so I'm not sure if there's a good reason for this. Since CPU's don't tend to run at a fixed frequency, is it even meaningful to define? I've not used FreeRTOS in this situation so I'm not sure what is customary.

The example build breakage this causes should be fixed regardless, it's just not clear to me what the right solution is.

**Comment by johnathancn** [comment]
I'm not sure what the use case is for getting the CPU clock, or more importantly why you'd expect FreeRTOS to provide this getter. The value is not used in the RTOS itself.

That said, if we can be convinced that this function belongs in this crate, what I'd suggest is a feature flag that gets set by the consuming application (I'm new to this but I assume it's easy enough), that would determine whether those functions are defined. Since the application must define this macro in FreeRTOSConfig for the thing to compile, the same application should enable the feature as well.

BTW in the PR I just set some dummy value so the thing compiles again, obviously not a real solution.

**Comment by schteve** [comment]
Yeah you're right `configCPU_CLOCK_HZ` isn't used in the Linux or Win port C files so it shouldn't be needed for these ports. I suspect `freertos_rs_get_configCPU_CLOCK_HZ()` is defined to allow the application to base other values on it, which if you were writing in C you could get directly from the header file that defines `configCPU_CLOCK_HZ`. So I would lean towards keeping it in.

I think this crate has the same issue lurking in a few places. FreeRTOS allows the optional inclusion of many different features via the `INCLUDE_x` defines. For example turning off `vTaskDelete` via `#define INCLUDE_vTaskDelete 0` triggers a similar build error. The Rust code expects a C function regardless of whether the config header includes it or not. So, it might be useful to treat this as a more general problem than just `configCPU_CLOCK_HZ`. Your feature flag suggestion sounds like it would work, not sure if there's any other obvious options I'm missing.

**Comment by schteve** [comment]
This could be a viable solution too. Let me poke around at it to see what it's like in a few scenarios. I definitely like the idea of keeping it so only the config header needs to be modified by the user since that's what FreeRTOS users are used to.

One focus here will be making sure things don't mysteriously break for the user in different situations. I recently found that the shim was missing some code but only the windows example broke. Want to avoid that type of thing where possible, and ideally the error messages would clearly point to the root cause as well. I'll try to take a closer look in the next few days.

**Comment by niondir** [comment]
I did not started with that but was thinking about the "feature flag" problem.
Since freertos is quiet configurable with it's configs and this configuration leads to changing Interfaces if the whole thing at compile time I guess every feature needs a feature flag in the cargo toml.

**Comment by schteve** [comment]
As I mentioned on #40 I was having some issues with building the `win` example if we just ifdef the function out. The linker is throwing an error because it's looking for `cpu_clock_hz()`, even though it's not used, and I'm still not clear why that is.

Extending this idea to other areas doesn't always have the same problem. For example the `shim.c` code already conditionally includes `vTaskDelay()` based on `INCLUDE_vTaskDelay`, and we can force the same type of situation by changing `INCLUDE_vTaskDelay` to 0 and removing this line in the `win` example: `CurrentTask::delay(Duration::ms(1000));` In this case it builds and runs with no complaints!

Further, I get similar linking issues for unrelated code in the `linux` example if I make slight changes to the example: removing `CurrentTask::delay(Duration::ms(1000));` causes link errors with `freertos_rs_pvPortMalloc`, `freertos_rs_spawn_task`, `freertos_rs_vTaskStartScheduler`, and others. I'm starting to think I'm missing something obvious because this doesn't make any sense to me at all - those functions weren't touched, and many are compiled unconditionally so should always be present.

I'm struggling to understand what the difference is between these situations, any insight is appreciated. One superficial difference is that `cpu_clock_hz()` is a module-level function while `CurrentTask::delay()` is part of a struct. But modifying `cpu_clock_hz()` to be in the same type of struct setup doesn't seem to make a difference (even placing it in `CurrentTask` right next to `delay()`.

**Comment by johnathancn** [comment]
resolved with #40
