### ISSUE TITLE
Possible incorrect timing for `CurrentTask::delay;` on stm32f411

### ISSUE THREAD

**Issue by barafael** [lobaro/FreeRTOS-rust#44]
First of all, thanks for your hard work on this project.

I took the stm32f411 black pill example and promoted it to a free-standing repo. I was very happy to see it works nicely with `defmt` and newer versions of the `stm32f4xx-hal`. However, I did observe that the blinking frequency is way higher than 1Hz.

https://github.com/barafael/really-fast-buttons/blob/a2081814e0dbff1d8ebc5d2aaa62761cebbb0252/freertos-tasks/src/main.rs#L70

More like 6Hz estimated. This was also the case before I upgraded the hal dependencies and set 

```
        let clocks = rcc.cfgr.use_hse(25.MHz()).sysclk(48.MHz()).freeze();
```

I'm not sure if this issue is even in the right place, perhaps I shouldn't touch the timer configuration when FreeRTOS already does it?

**Comment by schteve** [comment]
You should be able to modify the timings before starting the scheduler. I suspect in this case the defines in `FreeRTOSConfig.h` need to be updated, specifically `configCPU_CLOCK_HZ`. It's currently set to 4.2 MHz but probably needs to match your sysclk setting.

Just as a side note, I've run into similar issues before when integrating crate examples, since some crates give examples using the systick as a timer (which FreeRTOS controls). That will show similar symptoms where timers aren't running at the expected rate. I don't see any of that going on in your code though.

I don't have blackpill hardware to test it on so let me know how it goes. It also makes me wonder if there's a way we can automatically check that the clocks match FreeRTOS's expectations - the frozen clocks struct could be used in this case but non-CM platforms might not have those.

**Comment by barafael** [comment]
Of course, I should have checked. Didn't think but it was there in plain sight. Thanks :)

**Comment by schteve** [comment]
Glad this worked! I'm wondering, does the unmodified black pill example blink at the correct frequency for you? I would like to update it if not.

**Comment by barafael** [comment]
I just tested it again. It does blink at a rate of 2Hz I think, meaning 4 toggles/second. It's close to one toggle a second if I set 
`#define configCPU_CLOCK_HZ				( 8000000UL ) //also systick runs at this frequency`
it's pretty close to 1Hz:

![image](https://user-images.githubusercontent.com/6966738/206854894-54f4392d-369e-42b7-9a10-24e70e067d48.png)

**Comment by schteve** [comment]
Thanks for checking! I'll open an issue on this to address at some point. Might be a good excuse for me to pick up a blackpill anyway.
