### ISSUE TITLE
Proper way to use queue from different threads

### ISSUE THREAD

**Issue by koija** [lobaro/FreeRTOS-rust#61]
What is the proper way to share a queue object between 2 threads? Creating a local queue in main function and passing references to it to the threads does not compile:

     let queue = Queue::<u8>::new(4).unwrap();
 
     let ref_queue_1 = &queue;
     let ref_queue_2 = &queue;
 
     Task::new()
         .name("blinker")
         .stack_size(128)
         .priority(TaskPriority(2))
         .start(move || {
             ref_queue_1.send(1, Duration::infinite());
         })
         .unwrap();
 
     Task::new()
         .name("printer")
         .stack_size(128)
         .priority(TaskPriority(2))
         .start(move || {
             let _ = ref_queue_2.receive(Duration::infinite());
         })
         .unwrap();
 
     FreeRtosUtils::start_scheduler();

Is there a method to achieve this that I am not aware of? Or the only way is to have a global mutex-protected queue that is accessed by both threads?

**Comment by schteve** [comment]
Right now I'm not sure if we have a great solution but I'll give you what I can. The error you're getting is probably that the queue variable doesn't live long enough. Making it live longer should do the trick.

There's many ways to do this - for an embedded program the most direct might be to just allocate it statically. We can use an `Option` for this since we don't have a const initializer for Queue. This gets a bit verbose and requires you to use unsafe because of the static.

```rust
static mut MY_QUEUE: Option<Queue<u8>> = None;

#[entry]
fn main() -> ! {
    unsafe { MY_QUEUE = Some(Queue::<u8>::new(4).unwrap()); }

    Task::new()
        .name("blinker")
        .stack_size(128)
        .priority(TaskPriority(2))
        .start(move |_| {
            let _ = unsafe { MY_QUEUE.as_ref().unwrap().send(1, Duration::infinite()) };
        })
        .unwrap();

    Task::new()
        .name("printer")
        .stack_size(128)
        .priority(TaskPriority(2))
        .start(move |_| {
            let _ = unsafe { MY_QUEUE.as_ref().unwrap().receive(Duration::infinite()) };
        })
        .unwrap();

    FreeRtosUtils::start_scheduler();
}
```

An alternative would be to use a standard type to do the work for you. This example uses `Arc` which does require allocation, but abstracts the unsafe for you.

```rust

extern crate alloc;
use alloc::sync::Arc;

#[entry]
fn main() -> ! {
    let queue = Arc::new(Queue::<u8>::new(4).unwrap());

    let ref_queue_1 = queue.clone();
    let ref_queue_2 = queue.clone();

    Task::new()
        .name("blinker")
        .stack_size(128)
        .priority(TaskPriority(2))
        .start(move |_| {
            let _ = ref_queue_1.send(1, Duration::infinite());
        })
        .unwrap();

    Task::new()
        .name("printer")
        .stack_size(128)
        .priority(TaskPriority(2))
        .start(move |_| {
            let _ = ref_queue_2.receive(Duration::infinite());
        })
        .unwrap();

    FreeRtosUtils::start_scheduler();
}
```

You could also try a crate like `spin` that creates a lightweight mutex for you.

At the end of the day, the value returned by `Queue::new()` is just a handle and so we should be able to copy it and send it across threads. Probably implementing Copy, Send, and Sync on the Queue handle is the correct solution. Then the user doesn't have to statically or dynamically allocate just to hold on to the queue handle, they can pass it around as needed.

**Comment by schteve** [comment]
I'll work on a PR for the Copy, Send, Sync impls soon. The 1-minute attempt doesn't work because internally the handles are type aliases (which aren't allowed to be impl'd against) so we need to move to using newtypes for the handle which requires some wider changes.

**Comment by schteve** [comment]
On second thought, implementing those traits on `Queue` might not make sense anyway since it has a `Drop` impl. Will have to think about what can be done to improve the ergonomics here.
